export const API_ERROR_CODES = {
  addressNotFound: 'ADDRESS_NOT_FOUND',
  authEmailAlreadyExists: 'AUTH_EMAIL_ALREADY_EXISTS',
  authInvalidCredentials: 'AUTH_INVALID_CREDENTIALS',
  authUnauthorized: 'AUTH_UNAUTHORIZED',
  categoryNotFound: 'CATEGORY_NOT_FOUND',
  cancellationRequestExists: 'CANCELLATION_REQUEST_EXISTS',
  cancellationRequestNotFound: 'CANCELLATION_REQUEST_NOT_FOUND',
  internalServerError: 'INTERNAL_SERVER_ERROR',
  orderCancelNotAllowed: 'ORDER_CANCEL_NOT_ALLOWED',
  orderEmpty: 'ORDER_EMPTY',
  orderNotFound: 'ORDER_NOT_FOUND',
  orderPaymentDemoAlreadyConfirmed: 'ORDER_PAYMENT_DEMO_ALREADY_CONFIRMED',
  orderPaymentDemoNotAllowed: 'ORDER_PAYMENT_DEMO_NOT_ALLOWED',
  orderStockChanged: 'ORDER_STOCK_CHANGED',
  orderUnavailableItems: 'ORDER_UNAVAILABLE_ITEMS',
  invalidEmail: 'INVALID_EMAIL',
  invalidPhone: 'INVALID_PHONE',
  passwordMismatch: 'PASSWORD_MISMATCH',
  passwordTooShort: 'PASSWORD_TOO_SHORT',
  paymentMethodNotFound: 'PAYMENT_METHOD_NOT_FOUND',
  productMediaUploadFailed: 'PRODUCT_MEDIA_UPLOAD_FAILED',
  productMediaUrlInvalid: 'PRODUCT_MEDIA_URL_INVALID',
  productNotFound: 'PRODUCT_NOT_FOUND',
  productCompareAtPriceInvalid: 'PRODUCT_COMPARE_AT_PRICE_INVALID',
  productCategoryInvalid: 'PRODUCT_CATEGORY_INVALID',
  productBenefitsRequired: 'PRODUCT_BENEFITS_REQUIRED',
  productIngredientsRequired: 'PRODUCT_INGREDIENTS_REQUIRED',
  productPriceInvalid: 'PRODUCT_PRICE_INVALID',
  productSkuExists: 'PRODUCT_SKU_EXISTS',
  productSkuInvalid: 'PRODUCT_SKU_INVALID',
  productSlugExists: 'PRODUCT_SLUG_EXISTS',
  productSlugInvalid: 'PRODUCT_SLUG_INVALID',
  productStockInvalid: 'PRODUCT_STOCK_INVALID',
  productUploadInvalidType: 'PRODUCT_UPLOAD_INVALID_TYPE',
  required: 'REQUIRED',
  validationFailed: 'VALIDATION_FAILED',
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
